model_params:
  name: 'ConditionalVAE'
  in_channels: 1
  num_classes: 40
  latent_dim: 128

data_params:
  data_paths: ['./test_once/test1_seismic.npy', './test_once/test2_seismic.npy', './train/train_seismic.npy']
  labels_paths: ['./test_once/test1_labels.npy', './test_once/test2_labels.npy', './train/train_labels.npy']
  train_batch_size: 64
  val_batch_size:  64
  # patch_size: 64
  num_workers: 4

# data_params:
#   data_path: "./"
#   train_batch_size: 64
#   val_batch_size:  64
#   patch_size: 64
#   num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  # scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 300

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"